/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404IndexRouteImport } from './routes/404/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AlertIndexRouteImport } from './routes/alert/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as PartnerIndexRouteImport } from './routes/partner/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as SelectionsIndexRouteImport } from './routes/selections/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404IndexRoute = R404IndexRouteImport.update({
  id: '/404/',
  path: '/404/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertIndexRoute = AlertIndexRouteImport.update({
  id: '/alert/',
  path: '/alert/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectionsIndexRoute = SelectionsIndexRouteImport.update({
  id: '/selections/',
  path: '/selections/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404/': typeof R404IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/alert/': typeof AlertIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/selections/': typeof SelectionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404IndexRoute
  '/admin': typeof AdminIndexRoute
  '/alert': typeof AlertIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/contact': typeof ContactIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/selections': typeof SelectionsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/user': typeof UserIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404/': typeof R404IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/alert/': typeof AlertIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/selections/': typeof SelectionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404/'
    | '/admin/'
    | '/alert/'
    | '/companies/'
    | '/contact/'
    | '/partner/'
    | '/profile/'
    | '/selections/'
    | '/tasks/'
    | '/user/'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/admin'
    | '/alert'
    | '/companies'
    | '/contact'
    | '/partner'
    | '/profile'
    | '/selections'
    | '/tasks'
    | '/user'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/404/'
    | '/admin/'
    | '/alert/'
    | '/companies/'
    | '/contact/'
    | '/partner/'
    | '/profile/'
    | '/selections/'
    | '/tasks/'
    | '/user/'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404IndexRoute: typeof R404IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AlertIndexRoute: typeof AlertIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SelectionsIndexRoute: typeof SelectionsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404/': {
      id: '/404/'
      path: '/404'
      fullPath: '/404/'
      preLoaderRoute: typeof R404IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert/': {
      id: '/alert/'
      path: '/alert'
      fullPath: '/alert/'
      preLoaderRoute: typeof AlertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selections/': {
      id: '/selections/'
      path: '/selections'
      fullPath: '/selections/'
      preLoaderRoute: typeof SelectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404IndexRoute: R404IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AlertIndexRoute: AlertIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SelectionsIndexRoute: SelectionsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  UserIndexRoute: UserIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
